### ISSUE TITLE
[Feature Request] Custom Autofill for specific job application forms

### ISSUE THREAD

**Issue by anthonyfabius** [EasyApp-RPI/EasyApp#29] opened 2023-09-20 06:38 UTC
### Describe the Feature

Certain companies will use premade popular job application forms for people to apply. Some of these are Greenhouse, Job Lever, Workday, LinkedIn Easy Apply and a few others. Most if not all of these have a prebuilt layout that most companies just copy and paste so if we detect one of them being used we don't really have to use an LLM to determine what to fill in certain sections and we can just inject straight into the page. There are obviously things that can go wrong, like workday sometimes has multiple page applications but we can worry about these edge cases once we get a general form of this feature working

### Screenshots

![image](https://github.com/EasyApp-RPI/EasyApp/assets/67553651/da61330e-cb0c-454f-a5ef-5178d11cf216)
This is what typical greenhouse forms look like. Obviously there is more content than this but all of the forms should be generally the same.

**Comment by anthonyfabius** [comment] 2023-09-20 06:46
Just realized this was a dupe of #25 . Just close both when the feature is finished.

**Comment by LeadFreeCandy** [comment] 2023-09-23 04:04
Duplicate of #25

**Closed as completed by LeadFreeCandy** 2023-09-23 04:04 UTC
Labels: duplicate, feature
